export VISUAL=vim
export EDITOR=vim

# Exports for Go
export GOPATH=~/dev/go
export PATH="$PATH:$GOPATH/bin"

# Exports for Rust
export RUST_SRC_PATH=/usr/local/src/rust/src
export PATH="$HOME/.cargo/bin:$PATH"

# Activator/Scala Exports
export PATH="$PATH:/opt/activator/bin"
